-- MySQL Script generated by MySQL Workbench
-- 10/19/16 08:14:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myping
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myping
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myping` DEFAULT CHARACTER SET utf8 ;
USE `myping` ;

-- -----------------------------------------------------
-- Table `myping`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myping`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myping`.`priority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myping`.`priority` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myping`.`site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myping`.`site` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  `url` VARCHAR(1500) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `last_seen` TIMESTAMP NULL,
  `priority_id` INT NOT NULL,
  PRIMARY KEY (`id`, `priority_id`),
  INDEX `fk_site_priority1_idx` (`priority_id` ASC),
  CONSTRAINT `fk_site_priority1`
    FOREIGN KEY (`priority_id`)
    REFERENCES `myping`.`priority` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myping`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myping`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `telegram_id` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myping`.`site_has_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myping`.`site_has_person` (
  `site_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`site_id`, `person_id`),
  INDEX `fk_site_has_person_person1_idx` (`person_id` ASC),
  INDEX `fk_site_has_person_site_idx` (`site_id` ASC),
  CONSTRAINT `fk_site_has_person_site`
    FOREIGN KEY (`site_id`)
    REFERENCES `myping`.`site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_site_has_person_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `myping`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myping`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myping`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` INT NULL,
  `label` VARCHAR(45) NULL,
  `description` VARCHAR(1500) NULL,
  `alert` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myping`.`verify`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myping`.`verify` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `site_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`id`, `site_id`, `status_id`),
  INDEX `fk_verify_site1_idx` (`site_id` ASC),
  INDEX `fk_verify_status1_idx` (`status_id` ASC),
  CONSTRAINT `fk_verify_site1`
    FOREIGN KEY (`site_id`)
    REFERENCES `myping`.`site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_verify_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `myping`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myping`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myping`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `seen` TINYINT(1) NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `verify_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `verify_id`),
  INDEX `fk_notification_user1_idx` (`user_id` ASC),
  INDEX `fk_notification_verify1_idx` (`verify_id` ASC),
  CONSTRAINT `fk_notification_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `myping`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_verify1`
    FOREIGN KEY (`verify_id`)
    REFERENCES `myping`.`verify` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
